### ISSUE TITLE
Support for proposed Schnorr BIP?

### ISSUE THREAD

**Issue by ChristopherA** [bcoin-org/schnorr#3]
Any plans to support https://github.com/sipa/bips/blob/bip-schnorr/bip-schnorr.mediawiki ?

**Comment by guggero** [comment]
@ChristopherA I have a first implementation here: https://github.com/guggero/bip-schnorr
Any input is very welcome.

**Comment by chjj** [comment]
@ChristopherA, bip-schnorr is now supported in bcrypto: https://github.com/bcoin-org/bcrypto/blob/master/lib/js/schnorr.js

It uses the native version from libsecp256k1-zkp and falls back to the JS impl if the native backend isn't available.

I'm going to archive this repo now.
